Discord Bot
prologin/gcc-contenus pull request #27
Opened 2020-08-18 17:18 UTC by Gabzcr

This a subject proposition for the 2020 edition of GCC (and later ones). 

The goal of this subject is to create a discord bot and give some first simple instructions (say hello world, react to a keyword).
It uses `discord` and `asyncio` python packages.

2020-08-19 11:23 UTC, alarsyo commented
This is a great idea, thanks!

I'm a bit worried about the additional complexity introduced in the code samples (python decorators, and async/await keywords, though these are explained in the tutorial).

I'm not sure what's the best way to approach this: discarding them as fancy magic doesn't feel right, but diving into the details of wrapping functions in decorators may be too advanced for our trainees :confused: 

One solution would be to provide a wrapper around the `discord` module, hiding these language constructs away. No idea if that would be ideal.

Thoughts?

2020-08-19 15:40 UTC, Gabzcr commented
Hi,
I'm not sure to understand the proposed solution. I am no expert on wrappers, though I do understand how they work and how to use them. I just don't see how to make them disappear in the code by "providing a wrapper around the `discord` module". Can you briefly explain it ? Do you have a reference I could use to learn and hide the wrappers away ?

More generally, I am not used to manipulating modules. Is it about creating a new module containing the discord module to change the way to use its functions ? If that is so, I fear it is above my skill. I can instead try to explain wrappers in the TD but since it is so complicated, it would be an isolated part at the end of the TD for the curious only, with warnings concerning the difficulty.

What do you think is best ?

2020-08-19 15:59 UTC, alarsyo commented
> I just don't see how to make them disappear in the code by "providing a wrapper around the discord module". Can you briefly explain it ? Do you have a reference I could use to learn and hide the wrappers away ?

Reading the code again, I'm not sure there's a clean way to do this :confused:. I was thinking about providing simpler abstractions wrapping the "ugly" API, but I know realize that it doesn't solve the problem of decorators, as the girls will still need to "register" their functions through a decorator anyway. Maybe others can chime in? @zuh0, thoughts?

> Is it about creating a new module containing the discord module to change the way to use its functions ?

This is what I had in mind, yes, at least to hide the async / await keywords. I'm not the most skilled python programmer either, but I'm sure some Prologin members would be happy to work on that.

> I can instead try to explain wrappers in the TD but since it is so complicated, it would be an isolated part at the end of the TD for the curious only, with warnings concerning the difficulty.

If hiding them isn't an option, then this would be great :) a bonus section on decorators for the ones willing to go further.

2020-08-24 15:13 UTC, alarsyo commented
> I added a lot of explanations about the code samples I gave. I detailed a bit of everything, from modules to wrappers to object oriented programming.

This looks even better, thanks!

I've asked other Prologin members to review the subject, to get a broader sample of opinions :)

I'll pull the changes locally and read the rendered subject

2020-08-24 15:32 UTC, alarsyo requested changes
A few formatting problems with the generated PDF

2020-08-24 15:32 UTC, alarsyo commented on 06_discord_bot/06_discord_bot.md
> +</center>
The LaTeX produced by pandoc doesn't seem to include these images :(

Here's how we do it in other subjects: https://github.com/prologin/gcc-resources/blame/master/05_projet_microbit/05_projet_microbit.md#L19

2020-08-24 15:32 UTC, alarsyo commented on 06_discord_bot/06_discord_bot.md
> +internet par exemple), changez le ! Gardez le dans un coin, on va aussi en
This could benefit from a footnote, explaining that anyone with the secret token can reply instead of our bot

2020-08-24 15:32 UTC, alarsyo commented on 06_discord_bot/06_discord_bot.md
> +```
Lines longer than ~80 columns don't fit in the page width of the generated PDF:
[06_discord_bot.pdf](https://github.com/prologin/gcc-resources/files/5118765/06_discord_bot.pdf)

2020-08-26 10:29 UTC, Gabzcr commented
I solved all problems due to format conversion to pdf. The images now appear correctly and no line is longer than 80 columns anymore. Also I added the explanatory footnote on the importance of a secret token.

For the images, I had to modify the gcc template to have both the captions and my images placed exactly where I needed them to be (by adding [H] option to all images in the tex file). This is a mere add of package and instruction in the header. Since I did not want to change the template by fear the other TDs might be affected, I copied it in the 06_discord_bot directory and made my changes here. Please note that if you consider my add an improvement, it is possible to replace the gcc.tex template file by this new file.

2021-08-19 15:57 UTC, Eriovir approved these changes
Really good introduction to discord bots, it might be a bit difficult for people that have trouble understanding some programming notions, but if it's well supervised by a gcc! organizer, I think it can be a great subject.

2021-08-19 15:57 UTC, Eriovir commented on 06_discord_bot/06_discord_bot.md
> +![Connection du bot](ims/im4.png){width=9cm height=1.5cm}
```suggestion
![Connexion du bot](ims/im4.png){width=9cm height=1.5cm}
```

2021-08-19 15:57 UTC, Eriovir commented on 06_discord_bot/06_discord_bot.md
> +La doc renseigne aussi sur les actions que vous pouvez demander
```suggestion
La documentation renseigne aussi sur les actions que vous pouvez demander
```

2021-08-19 15:57 UTC, Eriovir commented on 06_discord_bot/06_discord_bot.md
> +Lire la doc et la comprendre peut être très difficile. N’hésitez pas à tester des choses par vous même et à demander autour de vous comment faire tel ou tel truc. Bonne programmation !
```suggestion
Lire la documentation et la comprendre peut être très difficile. N’hésitez pas à tester des choses par vous même et à demander autour de vous comment faire tel ou tel truc. Bonne programmation !
```

2021-08-19 15:57 UTC, Eriovir commented on 06_discord_bot/06_discord_bot.md
> +### Bon Courage !
```suggestion
### Bon courage !
```

2021-08-20 04:28 UTC, Elfikurr commented
Hello,

I (finally) read your work and it's very good !

If I had to add something :

Maybe we could put some intermediary exercices in order to get them acquainted with `async` and `await`. Even if they do not understand them completely, they will have to use them a bit, and adding some more guided practice before starting might be a good thing ?

Thanks again for this :)

2022-06-02 15:52 UTC, Gabzcr commented
Hi !

Thanks for the review ! But I don't agree with all of your points.

First, I am already using discord.py, and the bot works really well as is. You can find my bot used as a reference in here : http://github.com/Gabzcr/NinjaBot‌ (it is currently deployed via heroku).
I even tested slash commandes a little while ago and it worked on my bot, I simply didn't want to use them since it was getting confusing fast in the quick search, with all the commands I wanted to add.
I'm not sure I know of "rewrite" or things like that, would you have a minimal example that could show the versions you're using ?

About the possibilities, yeah this is not going really far. But we gave that TP 2 years already and it takes time to get there already ! Especially those wanting to code a "pendu" or other complicated game.
However, I would be more than happy to add things up if you have suggestions.

Sincerely,
Gabrielle
 

De : "El Laggron"
A : "prologin/gcc-resources" ,"Gabrielle Pauvert" ,"Author"
Envoyé: jeudi 2 Juin 2022 15:18
Objet : Re: [prologin/gcc-resources] Discord Bot (#27)
 

 

Hey,

Great idea to have a TP for Discord bots, and I hope I can help to get this PR ready!

I have a lot of experience in Discord bots development in Python, and noticed a few things.

Seriously outdated

To begin with, the version you're using, referred to as "async" or 0.16.X, is outdated since 2019. The branch is not updated at all and running this bot today will never work, as the gateway has gone through a lot of changes.

When the PR was opened, it was advised to use the new version 1.0, or "rewrite", for Python Discord bots, which still works today and is used for most bots.

However, since the rewrite of 2019, a new major version is already on the way, and will be released very soon, simply named "discord.py 2.0" (yes it's confusing). It's not officially out yet, but this version should definitely be used, as it brings the interactions to bots, which means the possibility to use slash commands, context commands, buttons, dropdown lists, modals, and more...

I think the TP should be rewritten for this new version (it just won't work otherwise). Of course it should start with simple text commands, and then progress towards simple interactions like buttons.

Not enough possibilities explored

This TP only explains how to do simple text commands, and react to messages sent. There is an insane amount of other interactions possible, not only with the new Discord interactions, but also simple events, reactions, or interacting with roles.

Of course, the TP should stay easy and accessible, but I think it should present more possibilities and invite the girls to create more stuff, while introducing them to reading the documentation.


Overall, I think a lot has to be redone with this TP. I'm not sure if you're still active, so I propose to write a new subject from scratch for Discord bots, as I believe it's a great idea to have this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-06-06 10:44 UTC, laggron42 commented
Hey !

My bad, your bot is using the correct version, but somehow followed practices from the previous version. For example using `pass_context=True` which is now True by default, or `msg.channel.send` where `ctx.send` is generally preferred, made me think you were using the previous, outdated version, but it works anyway.

If you want to use slash commands, or other interactions, the best is to upgrade to discord.py 2.0, it's not released yet but it's very stable, you can find the docs [here](https://discordpy.readthedocs.io/en/latest/) (and more specifically [here](https://discordpy.readthedocs.io/en/latest/interactions/api.html) for interactions), and install it using `pip install -U git+https://github.com/Rapptz/discord.py.git`.

----

I keep thinking about how we could use interactions in this TP. They're harder to use, but this can lead to a quick and satisfying result. Basically, there are two ways of doing this: class based, or event based. Let me show a button for example

```py
# class-based interactions
# recommended by the lib
class MyOwnButton(discord.ui.Button):
  async def callback(self, inter):
    await inter.response.send_message("You clicked on me!")


# event-based interactions
# maybe easier without classes ? not preferred for real use
async def a_random_function(bot):  # bot can be obtained with ctx.bot
  button = discord.ui.Button(custom_id="my-button", ...)
  inter = await bot.wait_for("interaction", check=lambda x: x.custom_id == "my-button")
  await inter.response.send_message("You clicked on me!")
  # will stop responding afterwards
```

Then, to use a button:
```py
button = MyOwnButton(label="Click here!", style=discord.ButtonStyle.green)
view = discord.ui.View()
view.add_item(button)
await ctx.send("Message content or something", view=view)
```
![image](https://user-images.githubusercontent.com/23153234/172125014-138bdf30-f693-44ad-b525-a7200c755750.png)

That's a lot of stuff to cover, but brings something new that can be fun to play with (and easier than reactions).

----

Other than interactions, I think it would be a good idea to introduce to documentation a bit more than that. Instead of dropping a link, maybe we could explain how to search and read things?

For example, suppose you have an exercice where you edit a role's name with `role.edit(name="something")`, then you could point the user to that part of the documentation, and ask them how to edit the color afterwards, gradually explaining how to understand and find stuff in this big page.

A Discord bot can do so many things, impossible to fit in a single TP, the key is to know how to ctrl+F the API ref, and find what we need to do anything.

What do you think?

2022-06-06 11:08 UTC, laggron42 requested changes
Putting my suggestions about interactions aside, there are a few things missing for the bot to function properly in 2022, as well as a few suggestions about the code itself.

If you don't have time to commit for these changes, don't hesitate to tell me, I'll try to change the required stuff on my end as I have a lot of free time currently!

2022-06-06 11:08 UTC, laggron42 commented on 06_discord_bot/06_discord_bot.md
> ++"description")
Now you need to specify the enabled intents.

See the comment above about intents. I only listed the 3 "privileged" intents, but there are way more. Discord advices you to only enable what you need, which will disable other useless events.

In the context of this TP, the easiest is probably to do this

```suggestion
bot = commands.Bot(command_prefix='!', description="ce que vous voulez en"
+"description", intents=discord.Intents.all())
```

They will have to tick ALL privileged intents prior to connecting the bot.

2022-06-06 11:08 UTC, laggron42 commented on 06_discord_bot/06_discord_bot.md
> +@bot.command(pass_context=True)
This is now `True` by default.
```suggestion
@bot.command()
```

2022-06-06 11:08 UTC, laggron42 commented on 06_discord_bot/06_discord_bot.md
> +    await msg.channel.send("Hello World !")
How about using `ctx.send` instead of `ctx.channel.send` (or `ctx.message.channel.send` here)?

2022-07-29 12:38 UTC, kolowy commented
@Gabzcr Do you want to continue this PR?

2022-07-29 15:04 UTC, Gabzcr commented
Maybe layter, but definitely not this year ^^. I'll gladly hand it over to someone else if there is someone motivated‌
 

De : "kolowy"
A : "prologin/gcc-resources" ,"Gabrielle Pauvert" ,"Mention"
Envoyé: vendredi 29 Juillet 2022 14:39
Objet : Re: [prologin/gcc-resources] Discord Bot (#27)
 

 

@Gabzcr Do you want to continue this PR?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-07-29 15:15 UTC, kolowy commented
Maybe @laggron42  can continue it? or I do?

2022-07-31 13:14 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/27

2022-07-31 13:14 UTC, closed without merging

2022-10-11 08:49 UTC, Gabzcr commented
Hi !

Thank you very much for you answers, I learned a few things reading you :)

Unfortunately, although I agree with the modifications you propose, I don't have time at all at the moment to make them and I probably won't have any next year (I will teach a class for the first time ^^).
Thus I trust you to build the TP on the subject. Feel free to start from what I had done more than two years ago or to start again from scratch, as you like :)

Thanks again !
 

De : "El Laggron"
A : "prologin/gcc-resources" ,"Gabrielle Pauvert" ,"Author"
Envoyé: lundi 6 Juin 2022 13:08
Objet : Re: [prologin/gcc-resources] Discord Bot (#27)
 

 

@laggron42 requested changes on this pull request.

Putting my suggestions about interactions aside, there are a few things missing for the bot to function properly in 2022, as well as a few suggestions about the code itself.

If you don't have time to commit for these changes, don't hesitate to tell me, I'll try to change the required stuff on my end as I have a lot of free time currently!


In 06_discord_bot/06_discord_bot.md:

> +Puis cliquez sur l’onglet `Applications` en haut à gauche.

+

+![Onglet Application](ims/im1.png){width=10cm height=6cm}

+

+Si vous ne possédez pas de compte discord, vous devez en créer un car cette action vous demandera de vous authentifier pour vous connecter à votre compte discord. Cliquez sur le bouton `New application` en haut à droite et entrez le nom de votre Bot pour le créer. Vous arrivez sur la page de votre bot, qui contient entre autres son identifiant (`ID`) dont vous aurez besoin pour la prochaine étape. Notez le quelque part, il servira !

+

+![ID du bot](ims/im2.png){width=12cm height=5cm}

+

+Cliquez ensuite sur l’onglet Bot à gauche puis sur `Add Bot`. Ici, vous

+verrez les informations de votre Bot, dont son pseudo (`username`) et son avatar que vous pourrez modifier selon vos envies, et surtout son token qui **doit toujours rester secret !** [^1] (sauf pour vous). Si votre token fuite (sur

+internet par exemple), changez le ! Gardez le dans un coin, on va aussi en

+avoir besoin pour plus tard. Et ne vous inquiétez pas pour le token de mon bot sur l'image, je l'ai changé après avoir mis ça ici.

+

+![Token du bot](ims/im9.png){width=12cm height=5cm}

+

+Voilà, votre bot est créé. Il faut maintenant le connecter à discord et lui donner du code à lire et exécuter.



It is now necessary to tick a few additional boxes when creating a bot, the intents.

As the traffic of bots grows more and more, Discord decided to restrict some informations to bots above 75 servers, unless justified. The bots created for this TP will never have to worry about that limit, but they still have to tick those boxes for certain features:


	Presence intent: Enables infos about a user's status (corresponding events and data)
	Server members intent: Allows the bot to view all the members from a server. If disabled, a member object may not exist in some situations (corresponding events and data)
	Message content intent: The most important one, allows a bot to see the content of a message. If disabled, all text commands and interactions are broken. This is inciting bot devs to use slash commands instead. (corresponding events and data)


Message content intent MUST always be enabled, unless you'd like to convert everything to slash commands :/


In 06_discord_bot/06_discord_bot.md:

> +Cliquez ensuite sur l’onglet Bot à gauche puis sur `Add Bot`. Ici, vous

+verrez les informations de votre Bot, dont son pseudo (`username`) et son avatar que vous pourrez modifier selon vos envies, et surtout son token qui **doit toujours rester secret !** [^1] (sauf pour vous). Si votre token fuite (sur

+internet par exemple), changez le ! Gardez le dans un coin, on va aussi en

+avoir besoin pour plus tard. Et ne vous inquiétez pas pour le token de mon bot sur l'image, je l'ai changé après avoir mis ça ici.



Discord tokens are now only shown on bot creation or token regeneration. It's worth adding a note about this change, they must keep their token as they won't be able to see it again.


In 06_discord_bot/06_discord_bot.md:

> +Pour interagir avec votre bot, lui donner des instructions et le tester, vous allez avoir besoin d’y accéder via discord. Nous allons l’inviter dans un

+serveur discord créé pour l'occasion. Vous pourrez supprimer ce serveur à la fin des tests si cela vous chante. Ouvrez discord (l'application que vous avez l'habitude d'utiliser) et créez un serveur de test en appuyant sur le `+` dans la barre de gauche en bas de vos serveurs.

+

+Ensuite, dans votre navigateur de recherche (par exemple firefox ou google chrome), tapez le lien suivant en remplaçant \[votre ID\] par l’ID de votre bot, sans guillemet. Normalement, vous avez noté cet ID dans un coin lors de la partie "Création du Bot".

+

+    https://discordapp.com/oauth2/authorize?client_id=[votreID]&scope=bot&

+    permissions=0



Discord now offers a URL generator built in the developers page. Instead of pasting a client ID, they can simply go to "OAuth2 > URL Generator", tick "bot", and they have their URL ready.


In 06_discord_bot/06_discord_bot.md:

> +Connecter son Bot

+==============

+

+Pour interagir avec votre bot, lui donner des instructions et le tester, vous allez avoir besoin d’y accéder via discord. Nous allons l’inviter dans un

+serveur discord créé pour l'occasion. Vous pourrez supprimer ce serveur à la fin des tests si cela vous chante. Ouvrez discord (l'application que vous avez l'habitude d'utiliser) et créez un serveur de test en appuyant sur le `+` dans la barre de gauche en bas de vos serveurs.

+

+Ensuite, dans votre navigateur de recherche (par exemple firefox ou google chrome), tapez le lien suivant en remplaçant \[votre ID\] par l’ID de votre bot, sans guillemet. Normalement, vous avez noté cet ID dans un coin lors de la partie "Création du Bot".

+

+    https://discordapp.com/oauth2/authorize?client_id=[votreID]&scope=bot&

+    permissions=0

+

+Vous devriez voir apparaître une page comme celle ci.

+

+![Page d'invitation du bot](ims/im3.png){width=6cm height=7cm}

+

+Sélectionnez le serveur dans lequel vous voulez inviter votre Bot, c'est à dire le serveur Test que nous venons de créer, et cliquez sur le bouton



Maybe worth noting that you need to have the "Manage server" (Gérer le serveur) permission on a server to add a bot?


In 06_discord_bot/06_discord_bot.md:

> +bot = commands.Bot(command_prefix='!', description="ce que vous voulez en"

++"description")



Now you need to specify the enabled intents.

See the comment above about intents. I only listed the 3 "privileged" intents, but there are way more. Discord advices you to only enable what you need, which will disable other useless events.

In the context of this TP, the easiest is probably to do this
⬇️ Suggested change

-bot = commands.Bot(command_prefix='!', description="ce que vous voulez en"

-+"description")

+bot = commands.Bot(command_prefix='!', description="ce que vous voulez en"

++"description", intents=discord.Intents.all())



They will have to tick ALL privileged intents prior to connecting the bot.


In 06_discord_bot/06_discord_bot.md:

> +

+qui s’exécute au lancement du Bot (et uniquement à ce moment là).

+

+Voilà, votre Bot apparaît désormais en ligne et connecté sur votre

+serveur de test. Mais pour l’instant, il ne fait rien. Nous devons lui

+donner des instructions.

+

+

+

+Une première commande : Hello World

+===================================

+

+Nous allons coder une commande appelée `bonjour` qui demande à notre bot d'envoyer un message `Hello World !`. Dans votre fichier python, à l’endroit où doivent figurer les commandes et instructions (repérées par un commentaire dans votre fichier si vous ne l’avez pas effacé), ajoutez le code suivant :

+

+``` python

***@***.***(pass_context=True)



This is now True by default.
⬇️ Suggested change

***@***.***(pass_context=True)

***@***.***()




I [...]