tp_reseau modifications
prologin/gcc-contenus pull request #36
Opened 2020-08-27 15:41 UTC by n1tsu

2020-11-03 21:46 UTC, tanguysegarra requested changes
client_envoi.py est le meme que ex5_client.py, je trouve ca un peu inutile d'avoir le meme fichier deux fois... et idem pour ex2_client.py qui est le meme que client_reception.py a un .strip() pres (qui ne sert pas a grand chose en plus a priori ici)

Aussi, si t'as la foi tu peux modifier les fichers de servers et refacto :) je crois que les decorateurs sont depreciated : des que tu lances le programme tu te prends un : `chat_server.py:14: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead` normalement :)

Sinon merci pour ton travail :)

2020-11-03 21:46 UTC, tanguysegarra commented on 03_reseau/03_reseau.md
> +**NB**: lisez les messages de façon ininterrompue jusqu'à ce qu'un message soit vide
ca fait plus de 80 colonnes...

2020-11-04 18:22 UTC, n1tsu commented
> client_envoi.py est le meme que ex5_client.py, je trouve ca un peu inutile d'avoir le meme fichier deux fois... et idem pour ex2_client.py qui est le meme que client_reception.py a un .strip() pres (qui ne sert pas a grand chose en plus a priori ici)

Effectivement c'est un peu bizarre. Après le réarrangement des fichiers avaient surtout pour but de facilement déployer les serveurs et de rapidement trouver les refs pour les exercices il me semble, du coup ca me choque pas tant que ca d'avoir des fichiers presque similaires mais qui correspondent aux numéros des exercices.

2020-11-04 19:03 UTC, Elfikurr commented
Deux petits détails : 
- il y a un shebang sur `client_reception.py`, `ex1_client.py`, `ex2_client.py` et `ex3_client.py`, mais pas sur les autres fichiers. Il faudrait donc soit les enlever sur ces fichiers, soit les rajouter sur les autres. (je me dis que de les avoir est mieux que de ne pas les avoir ?)
- dans `ex5_client.py`, on peut enlever la variable `exit` pour faire un simple `while True` avec un `break` (comme c'est fait dans tous les autres exos).

Pour le fait d'avoir des fichiers qui sont les mêmes, mais juste renamed différemment, tu as raison que pour plus de simplicité on pourrait les garder, mais on pourrait peut-être rajouter une ligne ou deux dans le README ?
Aussi, la seule différence entre les fichiers (2 à 2) sont le port sur lequel ils se connectent (en plus du `.strip()`).
Donc on peut très bien les laisser pour tester plus facilement, même si l'intérêt est moindre.

Dernière chose, il faudrait ajouter 2 choses sur ce TP, une très simple : si on envoie un espace ou qu'on spam "Entrée", ça spam le serveur, donc pas ouf (juste un `.strip()`) suffit ; deuxième point, il n'y a pas de rate limiting de notre côté pour empêcher les gens de spam, on devrait en implémenter un petit, ne serait-ce que pour que notre serveur ne décède pas quand quelqu'un le spam (sans trop l'empêcher de spam, pour que les participantes puissent faire un antispam côté client ! :D)

Merci beaucoup pour cette PR, et notamment pour avoir fix les async !

2020-11-12 17:09 UTC, Elfikurr commented
Après avoir changé les `.format` en f-strings et le rate limiting à 10 messages par secondes, c'est bon pour moi :)
Petite question sur ce dernier, est-ce qu'on signifie à l'utilisateur/utilisatrice que son message a été denied car trop de spam ?

2020-11-12 20:16 UTC, n1tsu commented
> Petite question sur ce dernier, est-ce qu'on signifie à l'utilisateur/utilisatrice que son message a été denied car trop de spam ?

Oui bonne idée, après de mon point de vue ce n'est pas forcement essentiel si on ajoute une rapide mention dans le sujet ou que les organisateurs explique ce point à l'oral.

2020-11-12 21:14 UTC, n1tsu commented
Je n'ai pas vraiment pu tester le message de warning pour le spam correctement, sachant qu'on l'envoie seulement a l'ip de la socket qui spam ca devrait être bon mais du coup je n'ai pas testé avec des clients ayant des ip différentes.

Il y a un autre probleme un peu plus important, c'est que pour le moment le rate limit du spam bloque les messages dépassant la limite, mais ne les supprime pas. En d'autre mots il les retiens un certains temps, puis relance le nombre de message autorisés, puis rebloque etc. Je ne sais pas a quel point c'est un problème.

2020-11-13 10:31 UTC, Elfikurr commented
Ah, tu veux dire que si quelqu'un envoie 500000 messages, ils vont être envoyés 10 par 10 ?
Je pense que c'est un peu chiant vu que ça sature le serveur x)

2022-07-31 13:15 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/36

2022-07-31 13:15 UTC, closed without merging