New exo: use Trie to create dico
prologin/gcc-contenus pull request #39
Opened 2020-11-14 17:36 UTC by amelie311098

2020-12-09 23:04 UTC, Elfikurr commented
@amelie311098 is this reviewable yet ? :D

2020-12-17 19:49 UTC, 71 commented
C'est ready à review ? Je vois des placeholders.

2020-12-17 19:50 UTC, Elfikurr commented
Oui c'est ready ! :)

2020-12-24 23:21 UTC, 71 requested changes

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +- si oui, on descend sur ce noeud et on cherche la prochaine lettre
```suggestion
- si oui, on descend sur ce noeud et on s'occupe de la prochaine lettre
```

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +42sh$ ./my_dict.py # le nom de votre fichier
> 42sh

oh noes

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +On peut créer une boucle avec le mot clé `while` ou avec le mot clé `for`.
Sous forme de bullet points ?

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +        if (i == 2)
```suggestion
        if i == 2:
```

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +Attention: Vous serez un peu moins guidé dans les bonus, donc n'hésitez pas
Dans les bonii ? :)

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +Conseil:
```suggestion
Conseils:
```

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +- Vous pouvez séparer les mots du fichier en utilisant le module `re` qui
Ça me paraît... lourd d'introduire `re` en une ligne dans un bonus. Après c'est vrai que Python n'a pas de `split` qui prenne une liste de patterns, mais c'est une bonne occasion de faire une petite loop :)

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +des mots dans le dictionnaire.
"... car il permet de diviser par deux le nombre de recherches nécessaires... à chaque recherche." or something.

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +Conseil:
```suggestion
Conseils:
```

2020-12-24 23:21 UTC, 71 commented on new_exo_trie_dictionary/exo_trie.md
> +- Si les 2 valeurs est égales, on a trouvé l'élément qu'on cherchait, on le
```suggestion
- Si les 2 valeurs sont égales, on a trouvé l'élément qu'on cherchait, on le
```

2021-05-21 23:17 UTC, RenjiSann requested changes
Quelques typos. Le sujet est sympa, ça me rappelle le DM huffman au S2. Sinon, j'ai eu un peu de mal en lisant le sujet à cerner ce qui est explicitement demandé de faire. Peut-être qu'inclure des lignes en gras du style *À toi de jouer!* et des #TODO dans les squelettes de code pourrait aider!

Des bisous ! et GG Amélie pour ce TP moult intéressant

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +On a déjà vu une première utilisateur du mot clé `for` avec l'algorithme de
```suggestion
On a déjà vu une première utilisation du mot clé `for` avec l'algorithme de
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +On peut également stopper la boucle sans modifier sa condition:
```suggestion
On peut également stopper la boucle sans modifier sa condition grâce au mot-clé _break_ (on casse la boucle):
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +            break # stop la boucle
```suggestion
            break # stoppe la boucle
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +- tester si un mot existe
```suggestion
- tester si un mot existe dans notre dictionnaire
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +- afficher la liste de mots contenu dans le dictionnaire
```suggestion
- afficher la liste des mots contenus dans le dictionnaire
```

ou bien (si c'est la liste et pas les mots qui sont contenus)

```suggestion
- afficher la liste de mots contenue dans le dictionnaire
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +elle s'utilise dans la documentation python. Il ne faut pas oubliez de fermer
Peut-être inclure une URL pour la doc python, histoire qu'elles se retrouvent pas sur des sites randoms en cherchant ?

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +- Vous pouvez récupérer les lignes du fichier une fois ouvert avec la méthode
```suggestion
- Une fois le fichier ouvert, vous pouvez récupérer une liste contenant chaque ligne avec la méthode
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +elle s'utilise dans la documentation python. Il ne faut pas oubliez de fermer
```suggestion
elle s'utilise dans la documentation python. Il ne faut pas oublier de fermer
```

2021-05-21 23:17 UTC, RenjiSann commented on new_exo_trie_dictionary/exo_trie.md
> +le fichier lorsqu'on n'en a plus besoin.
```suggestion
le fichier lorsque l'on n'en a plus besoin.
```

2022-07-31 13:16 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/39 :D

2022-07-31 13:17 UTC, closed without merging