Tp images
prologin/gcc-contenus pull request #51
Opened 2021-05-06 18:51 UTC by mayaelgemayel

2021-05-13 13:59 UTC, mayaelgemayel reviewed
Le TP est génial \o/ Il est bien organisé et mets en avant tous les filtres basiques intéressant que les filles adoreront tester sur des images. La plupart des commentaires sont des commentaires mineures sur les formulations et des oublis d'explication (elles ne connaissent pas forcement la mediane, les voisinages, etc...). Hate de voir la suite (conclusion + bonus) :D

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**But : Ecrire la fonction ``Negative(color)`` qui applique un filtre négatif sur une couleur. La fonction doit retourner la nouvelle couleur. **
```suggestion
**But : Écrire la fonction ``Negative(color)`` qui applique un filtre négatif sur une couleur. La fonction doit retourner la nouvelle couleur.**
```

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**But : Ecrire la fonction ``SymmetryX(image)`` qui applique une symétrie en X sur une image. La fonction doit retourner une nouvelle image. **
```suggestion
**But : Écrire la fonction ``SymmetryX(image)`` qui applique une symétrie en X sur une image. La fonction doit retourner une nouvelle image.**
```
On pourrait rajouter un schema qui explique la symetrie en X et en Y. Par exemple, un petit schema de 4 pixels suivi de la symetrie en X puis en Y:

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**But : Ecrire la fonction ``SymmetryY(image)`` qui applique une symétrie en Y sur une image. La fonction doit retourner une nouvelle image. **
```suggestion
**But : Écrire la fonction ``SymmetryY(image)`` qui applique une symétrie en Y sur une image. La fonction doit retourner une nouvelle image.**
```

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**But : Ecrire la fonction ``RotateN(image, n)`` qui applique N fois une rotation droite (90 degres) sur une image. La fonction doit retourner une nouvelle image. **
```suggestion
### Exercice 7 : Rotation

**But : Écrire la fonction ``RotateN(image, n)`` qui applique N fois une rotation droite (90 degres) sur une image. La fonction doit retourner une nouvelle image.**
```
Idee de bonus rotation d'angle de 0 a 360 degre ?

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +Exemple : Pour ``Diff(ref_image, noisycat)`` le resultat doit être de 3%.
```suggestion
Exemple : Pour ``Diff(ref_image, noisycat)``, avec ``ref_image`` étant l'image de référence et ``noisy_cat`` l'image ci-dessus contenant du bruit, le resultat doit être de 3%.
```
Ma formulation n'est pas geniale mais on ne sait pas encore ce que noisy_cat est et comment l'avoir (la donner avec le TP, la generer avec quelques lignes qui rajoute du bruit, ...) + elles ne savent pas forcement comment calculer le pourcentage de difference :)

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**Rappel : La mediane correspond à la valeur du (n + 1)/2 ième nombre de de cette liste**.
```suggestion
Rappel : La médiane est la la valeur qui sépare une distribution ordonnée en deux groupes de
 taille égale. Donc pour la retrouver dans notre cas, on trie en ordre croissant les valeurs des pixels intéressants et la médiane correspondra à la valeur au milieu de cette liste (à la position (nombre total d'éléments) / 2)
```
A mon avis, ce rappel devrait etre au dessus de l'exemple.

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +### Exercice 9 : Réduction de bruit
A mon avis cet exo devrait avoir la forme suiviante:

- But de l'exercice
- Explication voisinage (avec schema) + precision que dans notre cas c est un voisinage pour un filtre 5x5 et non 3x3
- Rappel mediane
- Exemple

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +*__Tips__ : Tu peux utiliser la fonction sort() de python pour trier une liste*
```suggestion
*__Conseil__ : Tu peux utiliser la fonction sort() de python pour trier une liste.*
```

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +Pour cet exercice vous allez devoir appliquer un filtre median sur l'image. Le filtre median remplace la couleur d'un pixel par la couleur de la valeur médiane des pixels de son voisinage et de lui-m
Pour etre consistant avec les autres exos, rajouter **But:...** sinon l'enlever des autres.

2021-05-13 13:59 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**But : Ecrire la fonction ``NoiseReduction(image)`` qui applique un filtre median sur une image. **
```suggestion
**But : Écrire la fonction ``NoiseReduction(image)`` qui applique un filtre median sur une image. **
```

2021-05-13 16:26 UTC, alarsyo commented on 07_images/07_images.md
> +PIL est une bibliothèque de traitement d'image écrite pour Python. C'est celle-ci que nous utiliserons durant toute la durée du TP afin d'appliquer nos filtres et manipuler les images.
ça va paraître tout bête mais est-ce qu'on leur a expliqué ce que c'était, très rapidement, une bibliothèque ? sinon ça mérite une parenthèse / une footnote pour leur dire que c'est, en gros, un ensemble de fonctions pratiques écrites par quelqu'un d'autre

2021-05-23 21:58 UTC, amelie311098 commented on 07_images/07_images.md
> +Pour cet exercice vous allez devoir appliquer un filtre median sur l'image. Le filtre median remplace la couleur d'un pixel par la couleur de la valeur médiane des pixels de son voisinage et de lui-m
Il me semble qu'ils ont pas vu ce que c'est le voisinage d'un pixel juste là, donc peut-être mettre une définition ou une image/schéma

2021-05-23 22:00 UTC, amelie311098 commented on 07_images/07_images.md
> +Nous remplaçons donc **25** par **14**.
le 25 c'est le 250 plus haut ?

2021-05-23 22:00 UTC, amelie311098 commented on 07_images/07_images.md
> +Prenons une matrice avec des valeurs aleatoires pour illustrer :
Manque une image ?

2021-05-23 22:01 UTC, amelie311098 commented on 07_images/07_images.md
> +Ici nous nous interessons aux de voisins de 250,
```suggestion
Ici nous nous intéressons aux voisins de 250,
```

2021-05-23 22:04 UTC, amelie311098 commented on 07_images/07_images.md
> +La valeur de chaque pixel va être déterminée par ses pixels voisins. Il donc suffit de "superposer" la matrice sur une partie de l'image, puis de faire la somme pondérée des valeurs des pixels voisin
```suggestion
La valeur de chaque pixel va être déterminée par ses pixels voisins. Donc il suffit de "superposer" la matrice sur une partie de l'image, puis de faire la somme pondérée des valeurs des pixels voisins, à l'aide de la matrice. On obtient ainsi la nouvelle valeur du pixel.
```

2021-05-23 22:05 UTC, amelie311098 commented on 07_images/07_images.md
> +Dans cette illustration, le pixel sélectionné est celui en bleu, de valeur 5. C'est la valeur de ce pixel qui changera en fonction du résultat de la somme pondérée. Les pixels voisins qui seront cons
```suggestion
Dans cette illustration, le pixel sélectionné est celui en bleu, de valeur 5. C'est la valeur de ce pixel qui changera en fonction du résultat de la somme pondérée. Les pixels voisins, qui seront considérés dans la somme pondérée, dépendent de la taille de la matrice, ils sont grisés sur le schéma. Voici comment on effectuerait le calcul :
```

2021-05-23 22:06 UTC, amelie311098 commented on 07_images/07_images.md
> +new = (-1)*3 + (-1)*8 + (-1)*11 + (-1)*6 + 8*5 + (-1)*8 + (-1)*3 + (-1)*2 + (-1)*6
Pour rendre les différentes parties du calcul plus explicites, peut-être prendre une matrice avec des coefficients uniques

2021-05-23 22:07 UTC, amelie311098 commented on 07_images/07_images.md
> +- si new < 0 alors new = 0
```suggestion
- si `new < 0` alors `new = 0`
```

2021-05-23 22:07 UTC, amelie311098 commented on 07_images/07_images.md
> +- si new > 255 alors new = 255
```suggestion
- si `new > 255` alors `new = 255`
```

2021-05-23 22:08 UTC, amelie311098 commented on 07_images/07_images.md
> +- si 0 < new < 255 alors new ne change pas
```suggestion
- si `0 < new < 255` alors `new` ne change pas
```

2021-05-23 22:11 UTC, amelie311098 commented on 07_images/07_images.md
> +- `path` la chaîne de caractères correspondant à l'image que l'on souhaite utiliser
```suggestion
- `path` la chaîne de caractères correspondant à l'emplacement de l'image que l'on souhaite utiliser dans l'ordinateur
```

2021-06-11 12:00 UTC, RenjiSann requested changes
👍 Le TP sera super sympa à réaliser je pense. 2-3 choses à modifier, mais dans l'ensemble ça passe, je trouve

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +**But : Écrire la fonction ``ApplyFilter(image, filter)`` qui applique le filtre donné en paramètre sur l'image. ``filter`` est une fonction qui prend une couleur et en retourne une nouvelle. Ce filt
peut-être donner un prototype de la fonction `filter`, style 
```
(R2, G2, B2) = filter((R1, G1, B1))
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +``Resultat = 0.2126 * Rouge + 0.7152 * Vert + 0.0722 * Bleu``
Préciser que `Resultat` est la nouvelle valeur des composantes RGB de la nouvelle couleur

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +Dans ce TP, nous utiliserons la représentation Rouge Vert Bleu (RVB ou RGB en anglais) pour donner une large palette de couleurs aux pixels de nos images.
Préciser que quand on parle de "couleur", c'est un triplet `(R, G, B)` où les 3 valeurs sont comprises entre 0 et 255

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +**But : Écrire la fonction ``SymmetryX(image)`` qui applique une symétrie en X sur une image. La fonction doit retourner une nouvelle image.**
```suggestion
**But : Écrire la fonction ``SymmetryX(image)`` qui applique une symétrie horizontale sur une image. La fonction doit retourner une nouvelle image.**
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +**But : Écrire la fonction ``SymmetryY(image)`` qui applique une symétrie en Y sur une image. La fonction doit retourner une nouvelle image.**
```suggestion
**But : Écrire la fonction ``SymmetryY(image)`` qui applique une symétrie verticale sur une image. La fonction doit retourner une nouvelle image.**
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +Exemple : Pour ``Diff(ref_image, noisycat)`` le resultat doit être de 3%.
+1 il faut expliquer un tout petit peu comment calculer la différence sur une image, je pense

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +## Bonus : convolution
```suggestion
## Bonus : Convolution
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +![](figures/sharp.png)
Ajouter une pitite conclusion ? 👉👈

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/filtres.ipynb
> +    "def RotateN(image, n):\n",
Dans cette fonction, tu renvoies le même objet `image` si n% 4 == 0 alors que tu renvoies une copie de l'image dans les autres cas.

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/07_images.md
> +**But : Écrire la fonction ``Diff(image1, image2)`` qui calcule le pourcentage de différence entre deux images. La fonction doit retourner un entier.**
```suggestion
**But : Écrire la fonction ``Diff(image1, image2)`` qui calcule le pourcentage de différence entre deux images de même dimensions. La fonction doit retourner un entier.**
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/filtres.ipynb
> +    "\t\t\t\t\tneighbour_b.append(p_image[i + k, j + l][2])\n",
⚠️ là tu dénoises pas les 2 pixels sur chaque bord

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/Convolution/convolution.ipynb
> +    "Première fonction : `isCoordValid(x, y, h, w)`, elle prend en paramètre des coordonnées `x`et `y`, ainsi que les dimensions de l'image `h` (hauteur / height en anglais) et `w` (largeur / width e
```suggestion
    "Première fonction : `isCoordValid(x, y, h, w)`, elle prend en paramètre des coordonnées `x` et `y`, ainsi que les dimensions de l'image `h` (hauteur / height en anglais) et `w` (largeur / width en anglais). Elle renvoie un booléen indiquant si les coordonnées sont bien dans l'image. "
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/Convolution/convolution.ipynb
> +    "Troisième fonction : `convolution(m, path, out)`, elle prend en paramètre `m`la matrice que l'on souhaite applique à l'image, `path` le chemin menant à l'image, soit une chaîne de caractères. Fi
```suggestion
    "Troisième fonction : `convolution(m, path, out)`, elle prend en paramètre `m` la matrice que l'on souhaite applique à l'image, `path` le chemin menant à l'image, soit une chaîne de caractères. Finalement, elle prend `out` qui est le nom de la nouvelle image créée."
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/Convolution/convolution.ipynb
> +    "Deuxième fonction : `makeValidValue(v)`, elle prend en paramètre un nombre décimal et renvoie un nombre entier. Elle fait en sorte de renvoyer une valeur entre 0 et 255. Si la valeur est inférie
```suggestion
    "Deuxième fonction : `makeValidValue(v)`, elle prend en paramètre un nombre décimal et renvoie un nombre entier. Elle fait en sorte de renvoyer une valeur entre 0 et 255. Si la valeur est inférieure à 0, elle renvoie 0. Si la valeur est supérieure à 255, elle renvoie 255."
```

2021-06-11 12:00 UTC, RenjiSann commented on 07_images/Convolution/convolution.ipynb
> +  }
```suggestion
```

2021-06-11 12:51 UTC, downvoteed commented on 07_images/filtres.ipynb
> +    "\t\t\t\t\tneighbour_b.append(p_image[i + k, j + l][2])\n",
J'ai ecrit dans le sujet que pour des raisons de simplicite les bords n'avaient pas a etre traite. J'ai peur que ca complique le sujet et que cet exercice dure trop longtemps. Aussi, de ce que j'ai vu il n'existe aucune norme sur la gestion ou non des bords dans le cadre d'un filtre median.

2021-07-18 19:55 UTC, RenjiSann requested changes

2021-07-18 19:55 UTC, RenjiSann commented on 07_images/07_images.md
> +Une bibliothèque est une collection de fonctions externes que tu peux importer pour les utiliser dans ton propre code.
```suggestion
Une bibliothèque est une collection de fonctions externes que tu peux importer pour utiliser dans ton propre code.
```
le sujet de la phrase est "collection", donc pas de "les"

2021-07-18 19:55 UTC, RenjiSann commented on 07_images/07_images.md
> +Le principe d'un filtre est de modifier la valeur des pixels d'une image pour appliquer un effet (noir et blanc, flou etc...).
```suggestion
Le principe d'un filtre est de modifier la valeur des pixels d'une image pour appliquer un effet (noir et blanc, flou, changement de luminosité, etc...).
```

2021-07-18 19:55 UTC, RenjiSann commented on 07_images/07_images.md
> +La fonction abs() permet d'obtenir la valeur absolue.
```suggestion
La fonction abs() permet d'obtenir la valeur absolue (toujours positive).
```

2021-07-18 19:55 UTC, RenjiSann commented on 07_images/07_images.md
> +pourcentage = 100 * ((diff/255) / (width * height * 3))
```suggestion
$$pourcentage = 100 \times \frac{diff}{width \times \height \times 3 \times 255}$$
```
Pour avoir une jolie formule LaTeX

2021-08-23 15:29 UTC, amelie311098 commented on 07_images/07_images.md
> +Résultat souhaité pour ``ApplyFilter(Grayscale, ref_image).save("Grayscale.jpg")``:
Les arguments sont inversés :sweat_smile:

2021-08-23 15:31 UTC, amelie311098 commented on 07_images/07_images.md
> +**But : Écrire la fonction ``RotateN(image, n)`` qui applique N fois une rotation droite (90 degres) sur une image. La fonction doit retourner une nouvelle image.**
```suggestion
**But : Écrire la fonction ``RotateN(image, n)`` qui applique N fois une rotation droite (90 degres dans le sens horaire) sur une image. La fonction doit retourner une nouvelle image.**
```

2021-08-23 15:41 UTC, amelie311098 commented on 07_images/07_images.md
> +Rappel : La médiane est la la valeur qui sépare une distribution ordonnée en deux groupes de taille égale. Donc pour la retrouver dans notre cas, on trie en ordre croissant les valeurs des pixels int
```suggestion
Rappel : La médiane est la valeur qui sépare une distribution ordonnée en deux groupes de taille égale. Donc pour la retrouver dans notre cas, on trie en ordre croissant les valeurs des pixels intéressants et la médiane correspondra à la valeur au milieu de cette liste (à la position : nombre total d'éléments / 2)
```

2021-08-23 16:06 UTC, amelie311098 commented on 07_images/07_images.md
> +Résultat souhaité pour ``ApplyFilter(Grayscale, ref_image).save("Grayscale.jpg")``:
Peut-être préciser que pour former du gris, R = G = B dans les valeurs des pixels

2021-08-25 09:00 UTC, mayaelgemayel commented on 07_images/07_images.md
> +**diff** est la variable à laquelle on affecte la différence entre les deux images pour chaque composante de chaque pixel.
```suggestion
- **(r1, g1, b1)** sont les valeurs correspondant aux couleurs de la première image.  
- **(r2, g2, b2) **sont les valeurs correspondant aux couleurs de la deuxième image.  
- **diff** est la variable à laquelle on affecte la différence entre les deux images pour chaque composante de chaque pixel.
```

2022-07-31 13:17 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/51

2022-07-31 13:17 UTC, closed without merging