Exercice avancé Micro:bit : Snake Game
prologin/gcc-contenus pull request #64
Opened 2021-12-22 16:20 UTC by RenjiSann

Petit sujet d'un exercice que j'ai proposé à certaines participantes pendant le stage de Rennes.
Le but est de faire un jeu Snake très simple, avec un serpent et des pommes générées aléatoirement une par une

2022-01-10 22:20 UTC, Nhqml approved these changes
J'ai beaucoup aimé lors du dernier GCC! donc ça me semble très bien de proposer ça, c'est relativement simple et plutôt bien expliqué.

Elles auront peut-être besoin d'un peu d'aide sur la fin mais ça peut les amener à réfléchir ensemble ou demander de l'aide donc je ne pense pas que ce soit une mauvaise chose.

J'ai fait quelques petites modifs (pour que le LaTeX rende bien, notamment) que je t'invite à review @RenjiSann :wink:

2022-01-10 22:20 UTC, Nhqml commented on microbit_snake/microbit_snake.md
> +- S'il n'y a pas de pomme sur le terrain, on en place une de manière aléatoire qui ne soit pas sur le terrain
```suggestion
- S'il n'y a pas de pomme sur le terrain, on en place une de manière aléatoire qui ne soit pas sur le serpent
```
J'imagine que c'est ce que tu as voulu dire ?

2022-01-10 23:19 UTC, RenjiSann commented on microbit_snake/microbit_snake.md
> +- S'il n'y a pas de pomme sur le terrain, on en place une de manière aléatoire qui ne soit pas sur le terrain
oui :)

2022-02-24 09:23 UTC, Elfikurr requested changes
Je trouve le sujet très sympa, je ne l'ai pas vu en action mais je peux voir pourquoi il a plu.

J'aimerai bien pouvoir le proposer en atelier tout seul, mais pour cela il manque pas mal de choses (il faut partir du principe qu'ils ne connaissent rien du coup).

Combien de temps prendrait l'atelier en standalone selon vous ?

2022-02-24 13:46 UTC, RenjiSann commented
> Je trouve le sujet très sympa, je ne l'ai pas vu en action mais je peux voir pourquoi il a plu.
> 
> J'aimerai bien pouvoir le proposer en atelier tout seul, mais pour cela il manque pas mal de choses (il faut partir du principe qu'ils ne connaissent rien du coup).
> 
> Combien de temps prendrait l'atelier en standalone selon vous ?


Si on part du principe qu'il faut tout expliquer, je pense que ça se fait en 2h30-3h max.
Donc à ajouter :
- Comment on manipule le micro-bit (récupérer les appuis de bouton, le système d'affichage avec les pixels et les coordonnées, le clear).
- Expliquer le jeu Snake en détails.

2022-02-28 11:24 UTC, Miyaou commented
- > Attention, la numérotation des lignes et des colonnes commence à 0.

Peut-être ajouter un exemple expliqué pour illustrer pour etre sur qu'ils comprennent. Par exemple, "ainsi, le pixel (0,2) correspond au pixel sur la 3e colonne de la 1e ligne".

- > Cette commande a le même effet que faire display.set_pixel(i, j, 0) 25 fois !

Des débutants risquent de ne pas forcément comprendre à quoi i et j font référence, on peut expliciter qu'il representent la ligne et la colonne.

- Indiquer quelque part que les TODO: correspondent a ce qu il faut faire à tel ou tel endroit, ou a chaque fois dire que cette explication correspond a tel ou tel TODO pourrait les aider

2022-07-29 12:14 UTC, amelie311098 requested changes
Stylé comme sujet, simple et efficace !
Un TP plutôt avancé du coup, ou en tout cas, il faut bien avoir compris le TP d'intro
Si on peut le terminer cet été, ce serait intéressant de le rendre disponible pour les GCC! de fin août

2022-07-29 12:14 UTC, amelie311098 commented on microbit_snake/microbit_snake.md
> +button_a.get_presses()  # Ces fonctions renvoient le nombres d'appuis effectués sur
```suggestion
button_a.get_presses()  # Ces fonctions renvoient le nombre d'appuis effectués sur
```

2022-07-29 12:14 UTC, amelie311098 commented on microbit_snake/microbit_snake.md
> +Maintenant, tu devrais être capable de faire bouger ton serpent sur le `micro:bit` en appuyant du les boutons ! Mais il n'y a pas encore de challenge car le serpent de grandit pas.
```suggestion
Maintenant, tu devrais être capable de faire bouger ton serpent sur le `micro:bit` en appuyant sur les boutons ! Mais il n'y a pas encore de challenge car le serpent ne grandit pas.
```

2022-07-29 12:14 UTC, amelie311098 commented on microbit_snake/snake.py
> +    # Si on appuie sur le bouton B, on tourne a droite. (UP-> RIGHT, RIGHT->DOWN...)
```suggestion
    # Si on appuie sur le bouton B, on tourne a droite. (UP->RIGHT, RIGHT->DOWN...)
```

2022-07-29 12:14 UTC, amelie311098 commented on microbit_snake/snake.py
> +# Tant que le serpent ne rempli pas toutes les cases de l'écran
```suggestion
# Tant que le serpent ne remplit pas toutes les cases de l'écran
```

2022-07-29 12:14 UTC, amelie311098 commented on microbit_snake/snake_ref.py
> +        if not (x, y) in snake:
Je crois pas que cette partie soit mentionnée dans le sujet, ce serait bien de le rajouter

2022-07-31 13:19 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/64

2022-07-31 13:19 UTC, closed without merging