New microbit basics
prologin/gcc-contenus pull request #68
Opened 2022-06-14 16:12 UTC by DaiF1

Un rework du premier TP microbit, avec de nouvelles explications et sans la partie qui fait docs à la fin

2022-06-14 22:19 UTC, amelie311098 requested changes
J'ai pas tout lu !
Stylé l'idée de narration au début,
Dans l'ensemble le sujet est vraiment bien, bien guidé
Peut-être un peu long si j'ai pas fini mais on peut rien faire pour ça je pense sinon faudrait skip des trucs
Mais en même temps il est plutôt bien aéré avec des vrais parties / images / code
Quelques trucs à relire et à corriger mais sinon ça me va !
Je finirai demain !

2022-06-14 22:19 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +Avec des blocs indentés de 1, 3 puis 2 espaces, python a du mal a comprendre ce
nani ????

2022-06-14 22:19 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +Avec des blocs indentés de 1, 3 puis 2 espaces, python a du mal a comprendre ce
aaah ! okay, mais pas écrit comme ça xD
y'a un exemple de code chétor juste après donc y'a sûrement pas besoin de cette phrase

2022-06-14 22:19 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +Pour l'instant il te suffit juste de savoir ça, je reviendrais là-dessus juste
```suggestion
Pour l'instant il te suffit juste de savoir ça, je reviendrai là-dessus juste
```

2022-06-14 22:19 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +du microbit, tu dois vouloir faire réagir ton programme en fonction de toutes
vouloir ?

2022-06-14 22:19 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +    display.scroll('x est inférieur à 50')
On peut expliciter que `x` est aussi supérieur à 30 du coup (pareil pour les autres)

2022-06-16 18:46 UTC, amelie311098 reviewed
C'est bon pour moi !

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +`while` suivi de la condition d'arrêt. Ici, la boucle s'arrêtera lorsque tu
```suggestion
`while` suivie de la condition d'arrêt. Ici, la boucle s'arrêtera lorsque tu 
```

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +boutons A et B avant que le logo tactile ne soit touché.
logo ? on a parlé de bouton tactile jusque là

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +- Il voudrait enfin que si trois doubles sont fait d'affilé, un smiley pas
```suggestion
- Il voudrait enfin que si trois doubles sont faits d'affilée, un smiley pas
```

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +de Joseph les une après les autres.
```suggestion
de Joseph les unes après les autres. 
```

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +  site d'entrainement à la programmation qui propose des leçons suivis de
```suggestion
  site d'entrainement à la programmation qui propose des leçons suivies de
```

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +- Prologin: un concours d'informatique pour les moins de 20 ans que nous
```suggestion
- Prologin : un concours d'informatique pour les moins de 20 ans que nous
```

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +x = display.get_pixel(2, 2)  # `x` vaut maintenant 9
Maybe changer 'x' par une autre lettre, vu qu'on parle de 'x' pour la colonne

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +<https://microbit-micropython.readthedocs.io/en/latest/image.html#attributes)>
```suggestion
<https://microbit-micropython.readthedocs.io/en/latest/image.html#attributes>
```

2022-06-16 18:46 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +display.scroll('Salut tous le monde !')  # affiche `Salut [...] !`
```suggestion
display.scroll('Salut tout le monde !')  # affiche `Salut [...] !`
```

2022-06-16 22:11 UTC, DaiF1 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +`while` suivi de la condition d'arrêt. Ici, la boucle s'arrêtera lorsque tu
C'est pas "le mot-clé `while`" qui est suivi ? Parce que c'est le tout qui forme la déclaration

2022-06-16 22:18 UTC, DaiF1 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +Si flash ce programme sur ton `micro:bit`, il affiche une barre de chargement sur la ligne de
J'ai rien dit j'avais mal lu

2022-06-16 22:36 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +`while` suivi de la condition d'arrêt. Ici, la boucle s'arrêtera lorsque tu
Ah si en effet, my bad

2022-06-23 17:13 UTC, amelie311098 requested changes
J'approuve les changes sauf un 👀

2022-06-24 10:46 UTC, DaiF1 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +/bin/bash: line 1: q: command not found
Oups...
Alors ça peut paraitre bizarre mais c'est un mistype. J'ai dû taper 'q:' au lieu de ':q' et il l'a executé et paste le résultat (étonnament c'est pas la première fois que ça arrive)

2022-06-24 10:52 UTC, DaiF1 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +/bin/bash: line 1: q: command not found
C'etait plutôt '!q' mais effectivement c'est un mistype
Par contre aucune idée de pourquoi il paste

2022-06-28 10:27 UTC, Alexandre-Voinier requested changes

2022-06-28 10:36 UTC, Gregoire-perso commented on 01_decouverte_micropython/01_decouverte_bis.md
> +Je me présente, je suis Joseph Marchand, et c'est moi qui vais t'accompagner au
What ? Depuis quand notre petit Joseph n’est plus de ce monde ?

2022-06-29 15:31 UTC, amelie311098 requested changes
J'ai pas tout relu, seulement les derniers changes et c'est bon pour moi 😉 
Il reste 2 commentaires en plus de celui ci et ça part en prod ! (ou en autre review 👀 )

2022-06-29 15:31 UTC, amelie311098 commented on 01_decouverte_micropython/01_decouverte_bis.md
> +    display.scroll('x est supérieur à 30 et inférieur à 50')
supérieur ou égal hein 👀

2022-07-28 15:20 UTC, amelie311098 commented
Hmm, il s'est passé quoi dans l'historique des commits ?
Mais si c'est bon pour le sujet, on pourra merge après avec verif

2022-07-31 13:20 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/68

2022-07-31 13:20 UTC, closed without merging