tp panier
prologin/gcc-contenus pull request #69
Opened 2022-06-21 10:26 UTC by kolowy

Ajout d'un nouveau Tp qui explique au maximum pour les personnes qui ont du mal.

2022-06-22 17:44 UTC, Gregoire-perso reviewed
C'est pas mal ça fait un petit sujet pas trop compliqué à faire pour les filles qui ont un peu de mal, sans pour autant leur donner le code à leur place. Après faudrait voir pour lier à la partie documentation.

2022-06-22 17:44 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Maintenant que nous avons défini notre fonction somme, nous allons vouloir l'utiliser. Pour ce faire rien de plus simple, il suffit d'appeler le nom de notre fonction avec les 2 nombres que nous voul
```suggestion
Maintenant que nous avons défini notre fonction `somme`, nous allons pouvoir l'utiliser. Pour ce faire rien de plus simple, il suffit d'appeler le nom de notre fonction avec les 2 nombres que nous voulons additionner en paramètre. 
```

Je sais pas si cette formulation est très claire. Peut-être plus quelque chose du style _il suffit d'appeler notre fonction en écrivant son nom suivi de ses paramètres entre parenthèse et séparés par une virgule._

2022-06-22 17:44 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +##
Pourquo y'a pas de titre ici ?

2022-06-22 17:44 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Bravo vous voila arrivé à la fin de ce projet !
```suggestion
Bravo te voilà arrivée à la fin de ce projet !
```

2022-06-22 23:02 UTC, amelie311098 requested changes
Bon TP,
Si la cible est les personnes en difficulté, on peut possiblement leur mâcher encore plus le travail (plus de code ou de bloc/schéma d'explication de code/ordre dans lequel exécuter les instructions)

Pour les fonctions, on peut leur montrer un vrai bout de code, et pas juste 2 lignes, qui leur montre à quoi ça sert en vrai
Là ça montre juste que ça existe et c'est cool s'ils veulent apprendre mais sans leur montrer l'intérêt

2022-06-22 23:07 UTC, amelie311098 commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour cela, il faut faire en sorte que tant que le joueur n'a pas perdu, alors le panier puisse bouger. Vous pouvez utiliser une variable booléenne pour cela.
Oh j'avais pas vu
Beaucoup de répétition de "pour cela" un peu partout aussi

2022-06-23 15:36 UTC, DaiF1 commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +##
Y a un titre en trop là non ?

2022-06-23 18:16 UTC, RGonon requested changes

2022-06-23 18:16 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour cela, n'oubliez pas de faire des conditions pour gérer les cas suivants :
```suggestion
Pour cela, n'oubliez pas de vérifier, à l'aide de conditions, les cas suivants : 
```

2022-06-23 18:16 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +>>> print (a)
```suggestion
>>> print(a)
```

2022-06-23 18:16 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Si la position de la pomme est sur la dernière ligne il faut alors gérer les deux cas suivants :
```suggestion
Si la position de la pomme est sur la dernière ligne, la plus basse, il faut alors gérer les deux cas suivants : 
```

2022-06-23 18:16 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour rendre la partie plus difficile et amusante, vous pouvez faire accélérer la vitesse de chute des pommes au cours du temps.
```suggestion
Pour rendre la partie plus difficile et amusante, vous pouvez faire augmenter la vitesse de chute des pommes au cours du temps. 
```

2022-06-23 18:16 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +##
```suggestion
```

2022-06-23 20:58 UTC, Swarwerth requested changes

2022-06-24 06:25 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +##
Les ## permettent de tracer un trait normalement

2022-06-24 14:16 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +##
```suggestion
---
```

2022-06-24 14:16 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +##
```suggestion
---
```

2022-06-24 14:16 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +
```suggestion
Avant de finir ce projet, vérifier d'avoir bien implémenté c'est différents éléments : 
* augmentation de la vitesse 
* best score
* pouvoir jouer normalement 
* relancer la partie


```

2022-06-24 16:40 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Il pourra vous être utile de réinitialiser l'écran et d'éteindre toutes les LEDs d'un coup. Pour cela, on utilise la fonction suivante.
```suggestion
Il pourra vous être utile de réinitialiser l'écran et d'éteindre toutes les LED d'un coup. Pour cela, on utilise la fonction suivante.
```

2022-06-27 10:13 UTC, RGonon requested changes

2022-06-27 10:13 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +    # expressions dans la boucle
```suggestion

#on initialise la variable `en_cours` à `True` 
en_cours = True   
x = 0

while en_cours: 
    # tant que la variable reste à vrai alors on évalue les 
    # expressions dans la boucle 
   
     # si x est égale à 5  
    if x ==5:
        #alors on met la variable en_cours à `False`
        en_cours = False
        # en_cours étant à `False` on sort de la boucle 
   
     # sinon on ajoute 1 à x
    else:
          x = x + 1
        
>>> print(x)
5
```

2022-06-27 15:02 UTC, RGonon requested changes

2022-06-27 17:11 UTC, RGonon requested changes

2022-06-27 17:11 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Maintenant ce rappel fait, passons au jeu !
```suggestion
```

2022-06-28 11:00 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Si la position de la pomme est sur la dernière ligne, la plus basse, il faut alors gérer les deux cas suivants :
```suggestion
Si la pomme est sur la dernière ligne, la plus basse, il faut alors gérer les deux cas suivants : 
```

2022-06-28 11:01 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +À l’aide de ce compteur, vous pourrez compter le nombre de pommes qui ont été attrapées et afficher ce score.
```suggestion
À l’aide de ce compteur, vous pourrez compter le nombre de pommes qui a été attrapé et afficher ce score.
```

2022-06-28 11:02 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Avant de passer à la partie suivante, veillez a vérifier ces différents points :
```suggestion
Avant de passer à la partie suivante, veillez à vérifier ces différents points : 
```

2022-06-28 11:18 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +>>>1==1
```suggestion
>>> 1==1
```

2022-06-28 11:18 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +# ce test nous renvoie le mot clé `True` donc l'affirmation 1=1 est vrai
```suggestion
# ce test nous renvoie le mot clé `True` donc l'affirmation 1=1 est vraie
```
Peut être inverser ce commentaire et le résultat de l'interpréteur

2022-06-28 11:19 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Une variable booléen peut  stocker le résultat de ce test ou simplement être initialisé à `True` ou `False`.
```suggestion
Une variable booléenne peut stocker le résultat de ce test ou simplement être initialisée à `True` ou `False`.
```

2022-06-28 11:19 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +>>>print(v_bool)
```suggestion
>>> print(v_bool)
```

2022-06-28 11:21 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +#on initialise la variable `en_cours` à `True`
```suggestion
# on initialise la variable `en_cours` à `True` 
```

2022-06-28 11:21 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +    # tant que la variable reste à vrai alors on évalue les
```suggestion
    # tant que la variable reste à `True`, on évalue les 
```

2022-06-28 11:22 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +     # si x est égale à 5
```suggestion
     # si x est égal à 5  
```
J'ai un petit doute la dessus

2022-06-28 11:22 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +    if x ==5:
```suggestion
    if x == 5:
```

2022-06-28 11:23 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +        #alors on met la variable en_cours à `False`
```suggestion
        # alors on met la variable `en_cours` à `False`
```

2022-06-28 11:23 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +        # en_cours étant à `False` on sort de la boucle
```suggestion
        # `en_cours` étant à `False` on sort de la boucle 
```

2022-06-28 11:24 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +>>> print(x)
Pas fan de mélanger code et interpréteur, les filles vont pas pouvoir tester ce code par elle même en faisant un copier - coller

2022-06-28 11:25 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Dès que le panier change de position il faut afficher sa nouvelle position sur l'écran. Ensuite il faut recalculer la position du panier.
On calcule pas d'abord la nouvelle position, et après on fait le changement ?

2022-06-28 11:26 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* si la plateforme dépasse vers la droite, que faire ?
Le panier plutôt non ?

2022-06-28 11:26 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* si la plateforme dépasse vers la gauche, que faire ?
Ici aussi du coup

2022-06-28 11:26 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Avant de passer à la partie suivante assurez vous d'avoir un panier pouvant bouger à droite et à gauche sur toute la ligne grâce aux boutons.
```suggestion
Avant de passer à la partie suivante, assurez-vous d'avoir un panier pouvant bouger à droite et à gauche sur toute la ligne grâce aux boutons.
```

2022-06-28 11:27 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +# générer un nombre entier "a" entre 0 et 4 inclus :
```suggestion
# générer un nombre entier `a` entre 0 et 4 inclus :
```

2022-06-28 11:27 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Le tuple peut être vue comme une boite avec deux valeurs à l'intérieur.
```suggestion
Le tuple peut être vu comme une boite avec deux valeurs à l'intérieur.
```

2022-06-28 11:28 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +L'utilisation d'un tuple va donc nous permettre de conserver la position du panier, la position horizontale en x et la position verticale en y, dans une variable qui sera notre boite.
C'est pas la position de la pomme qui est stockée par le tuple ?

2022-06-28 11:29 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Vous pouvez maintenant faire apparaitre une pomme de manière aléatoire, changer son emplacement. À chaque tour, la pomme doit descendre sur l'axe vertical.
```suggestion
Vous pouvez maintenant faire apparaître une pomme de manière aléatoire et changer son emplacement. À chaque tour, la pomme doit descendre sur l'axe vertical.
```
Chaque tour de boucle ?

2022-06-28 11:30 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +- la position est la même que celle de la pomme alors le joueur a réussi, et il faut faire apparaître une nouvelle pomme sur l'écran.
La position de la pomme est la même que celle de la pomme ? :p

2022-06-28 11:30 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +À l’aide de ce compteur, vous pourrez compter le nombre de pommes qui ont été attrapées et afficher ce score.
```suggestion
À l’aide de ce compteur, vous pourrez compter le nombre de pommes qui a été attrapé et afficher ce score.
```

2022-06-28 11:31 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Avant de passer à la partie suivante, veillez a vérifier ces différents points :
```suggestion
Avant de passer à la partie suivante, veillez à vérifier ces différents points : 
```

2022-06-28 11:31 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour finir cette partie, vérifier que si l'on n'attrape pas la pomme, la partie se termine bien et affiche le score.
```suggestion
Pour finir cette partie, vérifiez que si l'on n'attrape pas la pomme, la partie se termine bien et affiche le score.
```

2022-06-28 11:32 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Une fois le jeu fini, vous pouvez ajouter plusieurs améliorations. Notez que chaque amélioration est réalisable indépendamment des autres.
Ajouter ici qu'il faut que leur jeu soit totalement fonctionnel, et qu'elles peuvent demander de l'aide si ce n'est pas le cas

2022-06-28 11:33 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour rendre la partie plus difficile et amusante, vous pouvez faire augmenter la vitesse de chute des pommes au cours du temps.
```suggestion
Pour rendre la partie plus difficile et amusante, vous pouvez augmenter la vitesse de chute des pommes au fur et à mesure de l'avancement de la partie. 
```

2022-06-28 11:34 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +## Rejouer et meilleur score
```suggestion
### Rejouer et meilleur score
```

2022-06-28 11:34 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +                      #fonction et ses arguments
```suggestion
                       # fonction et ses arguments 
```

2022-06-28 11:34 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +                     # le résultat de l'addition
```suggestion
                      # le résultat de l'addition
```

2022-06-28 11:35 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Vous remarquerez que l'appel de notre fonction ne fais rien. C'est normal car ce que nous ne faisons rien du résultat de notre fonction. Plusieurs possibilités s’offrent à nous, nous pouvons afficher
Dans l'interpréteur, ça ne va pas rien faire, ça va afficher la valeur que renvoie la fonction

2022-06-28 11:36 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* best score
```suggestion
* meilleur score
```

2022-06-28 11:37 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* pouvoir jouer normalement
J'ai pas compris à quelle amélioration ça faisait référence

2022-06-28 11:37 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Bravo te voilà arrivée à la fin de ce projet !
```suggestion
Bravo vous voilà arrivée à la fin de ce projet !
```

2022-06-28 13:03 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +
Pour l'instant on se contente d'expliquer le principe du jeu, je pense pas que ca soit une bonne idée
//en soit avec les dessins ca me semble logique

2022-06-28 13:06 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +    # les expressions à l'intérieur de la condition
```suggestion
    # les expressions à l'intérieur de la condition
    print("Condition réalisée") 
```

2022-06-28 13:11 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +5
```suggestion
print(x)
# Vous pouvez constater qu'à la fin de cette boucle 
# la variable x a une nouvelle valeur : 5
```

2022-06-28 13:13 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* si la plateforme dépasse vers la droite, que faire ?
```suggestion
* si la panier dépasse vers la droite, que faire ?
```

2022-06-28 13:13 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* si la plateforme dépasse vers la gauche, que faire ?
```suggestion
* si la panier dépasse vers la gauche, que faire ?
```

2022-06-28 13:19 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +L'utilisation d'un tuple va donc nous permettre de conserver la position du panier, la position horizontale en x et la position verticale en y, dans une variable qui sera notre boite.
```suggestion
L'utilisation d'un tuple va donc nous permettre de conserver la position des pommes, la position horizontale en x et la position verticale en y, dans une variable qui sera notre boite. 
```

2022-06-28 13:27 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +>>> somme(2, 4)
```suggestion
somme(2, 4)
```

2022-06-28 13:28 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Vous remarquerez que l'appel de notre fonction ne fais rien. C'est normal car ce que nous ne faisons rien du résultat de notre fonction. Plusieurs possibilités s’offrent à nous, nous pouvons afficher
Ouaip mb je modifie ca

2022-06-28 13:31 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +5
```suggestion
print(somme(2, 3))
# résultat affiché dans la console : 5

resultat = somme(2, 3)
print(resultat)
# résultat affiché dans la console : 5
```

2022-06-28 14:11 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Dès que le panier change de position il faut afficher sa nouvelle position sur l'écran. Ensuite il faut recalculer la position du panier.
Ça revient au même en soi ? mais oui c'est probablement plus clair dans l'autre sens.

2022-06-28 14:14 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Vous pouvez utiliser la fonction `sleep(time)` pour attendre entre chaque tour. Nous vous conseillons de mettre la valeur `time` dans une variable et de la définir au début de votre code.
```suggestion
Vous pouvez utiliser la fonction `sleep(time)` pour attendre entre chaque tour. Nous vous conseillons de mettre la valeur `time` dans une variable et de la définir au début de votre code.

Mettre cette valeur dans une variable nous permettra de la changer, ce qui va nous etre utile dans la suite du programme.
```

2022-06-28 14:23 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +- la position est la même que celle de la pomme alors le joueur a réussi, et il faut faire apparaître une nouvelle pomme sur l'écran.
tsss

```suggestion
- la position est la même que celle du panier alors le joueur a réussi, et il faut faire apparaître une nouvelle pomme sur l'écran.
```

2022-06-28 14:25 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +
```suggestion
Avant de commencer cette partie vérifiez que votre jeu fonctionne correctement. Si ce n'est pas le cas n'hésite pas à demander de l'aide aux organisateurs !
`

2022-06-28 14:26 UTC, kolowy commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* pouvoir jouer normalement
??
Il faut que leur jeu marche en général.

2022-06-28 16:08 UTC, Gregoire-perso commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* pouvoir jouer normalement
Ah oui ok, je comptais pas ça comme un truc à vérifier à la fin

2022-06-30 10:55 UTC, RGonon requested changes

2022-06-30 10:55 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Dès que le panier change de position il faut afficher sa nouvelle position sur l'écran. Ensuite il faut recalculer la position du panier.
```suggestion
Dès que le panier change de position, il faut calculer la nouvelle position du panier.  Ensuite il faut afficher sa nouvelle position sur l'écran.
```

2022-06-30 12:35 UTC, Nhqml requested changes
À part quelques typos ou tournures étranges, le sujet est clair, intéressant et me semble suffisamment bien expliqué/accompagné :ok_hand:

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour ce faire, commençons par créer une variable `posPanier` qui sera la position du panier en X. Au début de la partie, le panier sera au milieu de l'écran, soit en position 2 (image ci-dessous).
```suggestion
Pour ce faire, commençons par créer une variable `pos_panier` qui sera la position du panier en X. Au début de la partie, le panier sera au milieu de l'écran, soit en position 2 (image ci-dessous). 
```

snake_case please

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +# ce test nous renvoie le mot clé `True` donc l'affirmation 1=1 est vraie
```suggestion
# ce test nous renvoie le mot clé `True` donc l'affirmation 1 = 1 est vraie
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +>>> v_bool = 1==1
```suggestion
>>> v_bool = 1 == 1
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +if vBool:
```suggestion
if v_bool:
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Dès que le panier change de position, il faut calculer la nouvelle position du panier.  Ensuite il faut afficher sa nouvelle position sur l'écran.
```suggestion
Dès que le panier se déplace, il faut calculer sa nouvelle position. Il faut ensuite le redessiner à l'écran à sa nouvelle position.
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +from random import *
```suggestion
# importer la fonction permettant de tirer un nombre aléatoire
from random import randint
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* avoir un score qui compte le nombre de pommes attrappées.
```suggestion
* avoir un score qui compte le nombre de pommes attrapées.
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +`
```suggestion

```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Une fois que nous avons choisi le nom de notre fonction et déterminé le nombre d'arguments néscessaires, nous pouvons définir le comportement de notre fonction.
```suggestion
*Notez qu'il est possible de définir des fonctions sans argument.*

Une fois que nous avons choisi le nom de notre fonction et déterminé ses arguments, nous pouvons définir le comportement de notre fonction. 
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +                      # le résultat de l'addition
```suggestion
    return nbr1 + nbr2 # Le mot clef `return` permet de renvoyer 
                      # le résultat de l'addition
```

Mettez vous d'accord sur l'orthographe de "mot clé"/"mot clef" aussi :eyes:

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +La fonction `somme` renvoie donc le résultat de la somme des deux nombres passés en paramètre.
```suggestion
La fonction `somme` renvoie donc le résultat de la somme des deux nombres passés en arguments. 
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Maintenant que nous avons défini notre fonction `somme`, nous allons pouvoir l'utiliser. Pour ce faire rien de plus simple, il suffit d'appeler le nom de notre fonction avec les 2 nombres que nous vo
```suggestion
Maintenant que nous avons défini notre fonction `somme`, nous allons pouvoir l'utiliser. Pour ce faire rien de plus simple, il suffit d'appeler le nom de notre fonction avec les 2 nombres que nous voulons additionner en arguments. 
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Mettre cette valeur dans une variable nous permettra de la changer, ce qui va nous etre utile dans la suite du programme.
```suggestion
Mettre cette valeur dans une variable nous permettra de la changer, ce qui va nous être utile dans la suite du programme.
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Ainsi, le joueur pourra relancer une partie en cliquant sur un bouton, ou arrêter le jeu en cliquant sur un autre.
```suggestion
Ainsi, à la fin d'une partie, le joueur pourra décider d'en relancer une en cliquant sur un bouton, ou d'arrêter le jeu en cliquant sur un autre. 
```

2022-06-30 12:35 UTC, Nhqml commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +* relancer la partie
```suggestion
Avant de finir ce projet, vérifiez d'avoir bien implémenté ces différents éléments : 
* pouvoir jouer normalement 
* augmentation de la vitesse
* relancer la partie
* meilleur score
```

2022-07-11 15:41 UTC, RGonon approved these changes

2022-07-13 07:51 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Vous pouvez maintenant faire apparaître une pomme de manière aléatoire et changer son emplacement. À chaque tour, la pomme doit descendre sur l'axe vertical.
C'est ajouté, tu en penses quoi ? ( 160 - 174 )

2022-07-13 07:51 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Plus simplement, vous pouvez voir une fonction comme une recette de cuisine.
je sais pas si les 6eme savent ce que c'est  (>_<)

2022-07-15 18:00 UTC, amelie311098 requested changes
Still qq typos 👀

2022-07-15 20:34 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Pour cela, tant que le joueur n'a pas perdu, on laissera le joueur faire bouger le panier. Vous pouvez utiliser une variable booléenne pour cela.
```suggestion
Pour cela, tant que le joueur n'a pas perdu, on laissera le joueur faire bouger le panier. Vous pouvez utiliser une variable booléenne.
```

2022-07-15 20:34 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Une variable booléenne peut donc être utilisée dans une condition ou comme condition d'arrêt d'une boucle.
```suggestion
Une variable booléenne peut donc être utilisée dans une condition (if) ou comme condition d'arrêt d'une boucle (while). 
```

2022-07-15 20:34 UTC, RGonon commented on 06_jeu_du_panier/06_jeu_du_panier.md
> +Une variable booléenne peut donc être utilisée dans une condition ou comme condition d'arrêt d'une boucle.
Vu le public qu'on vise avec ce TP autant que ca soit le plus claire possible tu as raison ;))

2022-07-15 20:34 UTC, RGonon commented on 06_jeu_du_panier/README.md
> +# TP Découverte Python
```suggestion
# TP Élémentaire Python
```

2022-07-16 11:01 UTC, maayaneaha reviewed
Le tp est clair et les participantes sont bien guidées
Il ne faudra pas oublier de le mettre en ligne pour qu'elles puissent y avoir accès pendant le stage

2022-07-17 18:13 UTC, Nhqml approved these changes

2022-07-18 17:27 UTC, amelie311098 requested changes

2022-07-18 17:27 UTC, amelie311098 commented on content/micropython/tp-panier/index.md
> +Une variable booléenne peut donc être utilisée dans une condition ou comme condition d'arrêt d'une boucle.
```suggestion
Une variable booléenne peut donc être utilisée dans une condition (`if`) ou comme condition d'arrêt d'une boucle (`while`).
```

2022-07-27 09:41 UTC, RGonon commented on content/micropython/tp-panier/index.md
> +Afin de vous faciliter le travail, nous vous conseillons d'utiliser une variable qui contiendra la position du panier. Ainsi vous pourrez plus facilement déterminer la nouvelle position du panier en
```suggestion
Afin de vous faciliter le travail, nous vous conseillons d'utiliser la variable `pos_panier`. Ainsi vous pourrez plus facilement déterminer la nouvelle position du panier en fonction des boutons pressés.
```

2022-07-27 09:41 UTC, RGonon commented on content/micropython/tp-panier/index.md
> +Afin de vous faciliter le travail, nous vous conseillons d'utiliser une variable qui contiendra la position du panier. Ainsi vous pourrez plus facilement déterminer la nouvelle position du panier en
Bonne idée, on pourra ajouter ca dans la cheat sheet du TP (j'ajoute ca dans le README)

2022-07-27 09:41 UTC, RGonon commented on content/micropython/tp-panier/README.md
> +
```suggestion
#TODO ajouter un rappel sur les bouttons dans la cheat sheet du TP
```

2022-07-27 16:55 UTC, MrCirdo reviewed
J'ai bien aimé le TP, je pense qu'il est cool à faire et que les filles peuvent bien s'amuser avec.
Notamment avec les parties bonus.

J'ai noté les choses qui me dérangaient.
Autre détail, certains commentaires commencent par une majuscule, d'autre par une minuscule et parfois finissent par un point.

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +Pour créer la pomme nous allons utiliser un `tuple`. Un tuple est couple de valeurs.
Pourquoi utiliser un `tuple` au lieu d'une liste ?

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +Le tuple peut être vu comme une boite avec deux valeurs à l'intérieur.
J'ai l'impression que la métaphore des boites est utilisée partout (fonction, variables, tuple, etc.).
Pour le coup, la métaphore qui s'en rapproche le plus est celle d'une liste.
```suggestion
Le tuple peut être vu comme une liste contenant des valeurs.
```

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +Pour cela, vous devez indiquer le nom de votre tuple puis, ouvrir des crochets pour indiquer l'élément auquel vous souhaitez accéder, et refermer les crochets.
```suggestion
Pour cela, vous devez indiquer le nom de votre tuple puis, ouvrir des crochets pour indiquer la position de l'élément auquel vous souhaitez accéder, et refermer les crochets.
```
Je trouve cela plus précis d'indiquer la postion de l'élément

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +*Attention vous devez indiquer le numéro auquel vous souhaitez accéder en lui soustrayant 1.*
```suggestion
*Attention le premier élément se situe à l'index `0` !!!*
```

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +### Les fonctions
`### Les fontions` est au même niveau que `### Rejouer et meilleur score`
```suggestion
#### Les fonctions
```

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +#### Exemple :
```suggestion
##### Exemple :
```
Il y a peut être trop de niveau du coup :)

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +                      # le résultat de l'addition
```suggestion
                       # le résultat de l'addition
```
Le comentaire n'est pas au même niveau que l'autre.

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +Une variable booléenne représente deux valeurs : `True` ou `False`.
On utilise ici la console Python. Cependant, elle est très vite introduit dans `mu-tutoriel`.
C'est peut-être une bonne chose de le rappeler ici.

2022-07-27 16:55 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +Dès que le panier se déplace, il faut calculer sa nouvelle position. Il faut ensuite le redessiner à l'écran à sa nouvelle position.
Dans la section `### Rapel`, on met aussi des astuces ?

2022-07-28 13:29 UTC, juli0z commented on content/micropython/tp-panier/index.md
> +Pour créer la pomme nous allons utiliser un `tuple`. Un tuple est couple de valeurs.
L'idée était de leur donner des éléments non modifiables, pour ne pas avoir à introduire les méthodes de la liste (append, pop, ...) pour faire le jeu, ce qui pourrait les embrouiller. Même si ça laisse moins de liberté, la structure des tuples sera la même tout au long de leur code. 
Ensuite, c'était un choix un peu arbitraire aussi ;)

2022-07-28 13:39 UTC, juli0z commented on content/micropython/tp-panier/index.md
> +Le tuple peut être vu comme une boite avec deux valeurs à l'intérieur.
Une liste est moins concret qu'une boite, c'est pour ça qu'on utilise des objets physiques. La boite est utilisée pour pas mal de points, parce que c'est un concept simple à comprendre. Ensuite si tu as d'autres idées d'objets physiques pour imager les tuples, ça peut être bien

2022-07-28 13:44 UTC, MrCirdo commented on content/micropython/tp-panier/index.md
> +Le tuple peut être vu comme une boite avec deux valeurs à l'intérieur.
Je pensais à une liste de course papier comme object physique. Je sais pas si ca peut t'aider.

2022-07-31 13:20 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/69 <3

2022-07-31 13:20 UTC, closed without merging