refonte pygame
prologin/gcc-contenus pull request #85
Opened 2022-07-19 16:22 UTC by kolowy

2022-07-27 13:09 UTC, amelie311098 requested changes
Les suggestions de la semaine dernière que j'avais pas envoyées
Globalement du français
Je lirai la 2e partie soon

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Enfin, pour afficher l'image, il faut utiliser la fonction `blit` sur l'objet `ecran` renvoyé par la fonction `pygame.display.set_mode` vu à la section ci dessi.
```suggestion
Enfin, pour afficher l'image, il faut utiliser la fonction `blit` sur l'objet `ecran` renvoyé par la fonction `pygame.display.set_mode` vu à la section ci dessous.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Votre programme devrait donc ressembler au code suivant:
```suggestion
Votre programme devrait donc ressembler au code suivant :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Cela se fait très simplement: il suffit de redessiner la même image à des emplacements différents.
```suggestion
Cela se fait très simplement : il suffit de redessiner la même image à des emplacements différents.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +La capture des touches du clavier peut se faire comme vu à la section [Évènements](#évènements), à l'aide de la fonction `pygame.event.get` tout comme `pygame.QUIT`, mais pour chaque touche du clavie
```suggestion
La capture des touches du clavier peut se faire comme vu à la section [Évènements](#évènements), à l'aide de la fonction `pygame.event.get` tout comme `pygame.QUIT`, mais pour chaque touche du clavier, Pygame a deux évènements : un lorsque la touche est enfoncée et un autre lorsque la touche est relachée.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Traiter les évènements de cette manière est très fastidieux, pour nous simplifier la tâche, une autre fonction est disponible: `pygame.key.get_pressed`.
```suggestion
Traiter les évènements de cette manière est très fastidieux, pour nous simplifier la tâche, une autre fonction est disponible : `pygame.key.get_pressed`.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour cela, chargez deux images: **image1** et **image2** et créez un tableau comme suit:
```suggestion
Pour cela, chargez deux images : **image1** et **image2** et créez un tableau comme suit :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour empêcher les mouvements hors de la carte, vous pouvez commencer par limiter la position de l'image lorsque celle-ci est déplacée: si une coordonnée passe en dessous de zéro, celle-ci est laissée
```suggestion
Pour empêcher les mouvements hors de la carte, vous pouvez commencer par limiter la position de l'image lorsque celle-ci est déplacée : si une coordonnée passe en dessous de zéro, celle-ci est laissée à zéro à la place.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Un bon endroit pour faire cela est dans la boucle de dessin de la carte: on commence avec une liste vide `solides = []`, puis pour chaque **i**, **j**, si `carte[i][j]` représente un objet solide, le
```suggestion
Un bon endroit pour faire cela est dans la boucle de dessin de la carte : on commence avec une liste vide `solides = []`, puis pour chaque **i**, **j**, si `carte[i][j]` représente un objet solide, le rectangle correspondant est ajouté à **solides**.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour tester s'il existe une intersection entre deux rectangles **r1** et **r2**, Pygame nous fournit la fonction:
```suggestion
Pour tester s'il existe une intersection entre deux rectangles **r1** et **r2**, Pygame nous fournit la fonction :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour pallier à cela, une fois que vous avez trouvé le rectangle solide avec lequel vous êtes en collision, vous pouvez effectuer un mouvement de la forme:
```suggestion
Pour pallier à cela, une fois que vous avez trouvé le rectangle solide avec lequel vous êtes en collision, vous pouvez effectuer un mouvement de la forme :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Finalement, pour gérer correctement les mouvements diagonaux, il vous est fortement conseillé de séparer votre détection de collision en deux parties:
```suggestion
Finalement, pour gérer correctement les mouvements diagonaux, il vous est fortement conseillé de séparer votre détection de collision en deux parties :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour écrire un texte à l'écran, il faut commencer par choisir la police d'écriture à l'aide de la fonction  `pygame.font.Font`, cette fonction prend deux arguments: le nom de la police d'écriture et
```suggestion
Pour écrire un texte à l'écran, il faut commencer par choisir la police d'écriture à l'aide de la fonction  `pygame.font.Font`, cette fonction prend deux arguments : le nom de la police d'écriture et sa taille.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +À partir d'une police d'écriture, il nous est possible de générer du texte avec `police.render` qui prend trois arguments: le texte à afficher, antialiasing [^2] et la couleur du texte.
```suggestion
À partir d'une police d'écriture, il nous est possible de générer du texte avec `police.render` qui prend trois arguments : le texte à afficher, antialiasing [^2] et la couleur du texte.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +On obtient alors un code de la forme:
```suggestion
On obtient alors un code de la forme :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Il faudra donc voir si l'un des évènements est l'appui sur le clic gauche:
```suggestion
Il faudra donc voir si l'un des évènements est l'appui sur le clic gauche :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Il est alors possible de récupérer la position de la souris avec la fonction `pygame.mouse.get_pos` qui renvoie une paire d'entiers $(x, y)$, la position relative au pixel en haut à gauche:
```suggestion
Il est alors possible de récupérer la position de la souris avec la fonction `pygame.mouse.get_pos` qui renvoie une paire d'entiers $(x, y)$, la position relative au pixel en haut à gauche :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +## Évènements aléatoires: le module **random**
```suggestion
## Évènements aléatoires : le module **random**
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Après avoir importé le module avec `import random` dans la partie initialisation, vous pouvez faire appel aux fonctions suivantes:
```suggestion
Après avoir importé le module avec `import random` dans la partie initialisation, vous pouvez faire appel aux fonctions suivantes :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +La fonction `random.randint` peut par exemple être utilisée pour simuler le lancer d'un dé à 6 faces:
```suggestion
La fonction `random.randint` peut par exemple être utilisée pour simuler le lancer d'un dé à 6 faces :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Par exemple, dans la partie initialisation vous pouvez ajouter:
```suggestion
Par exemple, dans la partie initialisation vous pouvez ajouter :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Puis lors de la gestion des appuis sur les touches du clavier (voir la section [Touches du clavier](#touches-du-clavier):
```suggestion
Puis lors de la gestion des appuis sur les touches du clavier (voir la section [Touches du clavier](#touches-du-clavier) :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +## Fluidité du jeu: fixer la durée d'une boucle
```suggestion
## Fluidité du jeu : fixer la durée d'une boucle
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Dans la partie initialisation, vous pouvez ajouter la ligne:
```suggestion
Dans la partie initialisation, vous pouvez ajouter la ligne :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Puis à la fin de la boucle de jeu vous pouvez faire:
```suggestion
Puis à la fin de la boucle de jeu vous pouvez faire :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +## Saut réaliste: vitesse et gravité
```suggestion
## Saut réaliste : vitesse et gravité
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +[^3]: N'oubliez pas de faire ça en deux fois: d'abord le déplacement horizontalement ($p_x$ est transformé en $p_x + v_x$), suivi de la résolution des collisions (voir section [Gestion des collisions
```suggestion
[^3]: N'oubliez pas de faire ça en deux fois : d'abord le déplacement horizontalement ($p_x$ est transformé en $p_x + v_x$), suivi de la résolution des collisions (voir section [Gestion des collisions](#gestion-des-collisions)), puis déplacement vertical, suivi d'une autre phase de résolution des collisions.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Le saut prendra donc la forme suivante:
```suggestion
Le saut prendra donc la forme suivante :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +## Mouvements réalistes: Animation des *sprites*
```suggestion
## Mouvements réalistes : Animation des *sprites*
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour gérer ça dans votre code, en plus de stocker la position du personnage comme vous devez déjà le faire, stockez également deux valeurs: la vitesse horizontale et la vitesse verticale.
```suggestion
Pour gérer ça dans votre code, en plus de stocker la position du personnage comme vous devez déjà le faire, stockez également deux valeurs : la vitesse horizontale et la vitesse verticale.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour animer un personnage, rien de plus simple: il suffit d'afficher une image différente à chaque tour de boucle du jeu.
```suggestion
Pour animer un personnage, rien de plus simple : il suffit d'afficher une image différente à chaque tour de boucle du jeu.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour les utiliser, il faut commencer par stocker dans une variable le tour de boucle actuel: initialisez une variable `tour_de_boucle` à 0, puis à chaque tour de boucle incrémentez là de 1.
```suggestion
Pour les utiliser, il faut commencer par stocker dans une variable le tour de boucle actuel : initialisez une variable `tour_de_boucle` à 0, puis à chaque tour de boucle incrémentez là de 1.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Pour simplifier l'écriture du code, il est bien plus facile de mettre les images dans un tableau, vous pouvez même utiliser une compréhension de liste (la syntaxe avec un `for` entre des crochets) po
```suggestion
Pour simplifier l'écriture du code, il est bien plus facile de mettre les images dans un tableau, vous pouvez même utiliser une compréhension de liste (la syntaxe avec un `for` entre des crochets) pour charger toutes les images à la fois [^4] :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Hormis cela, les autres touches disponibles sont:
```suggestion
Hormis cela, les autres touches disponibles sont :
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Celle-ci prend un second argument: une paire `(w, h)`, la nouvelle taille de l'image.
```suggestion
Celle-ci prend un second argument : une paire `(w, h)`, la nouvelle taille de l'image.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Celle ci prend un total de trois arguments: l'image, est ce qu'elle doit être renversé horizontalement et est ce qu'elle doit être renversé verticalement.
```suggestion
Celle ci prend un total de trois arguments : l'image, est ce qu'elle doit être renversé horizontalement et est ce qu'elle doit être renversé verticalement.
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Celle-ci prend un second argument: l'angle de rotation (dans le sens trigonométrique, c'est-à-dire anti-horaire).
```suggestion
Celle-ci prend un second argument : l'angle de rotation (dans le sens trigonométrique, c'est-à-dire anti-horaire).
```

2022-07-27 17:00 UTC, kolowy commented on content/divers/projet_jeu/index.md
> +Vous trouverez à peu prêt les mêmes sprites pour les deux personnages suivant:
```suggestion
Vous trouverez à peu prêt les mêmes sprites pour les deux personnages suivant :
```

2022-07-27 18:29 UTC, MrCirdo reviewed
Le tp est bien, il y a beaucoup de notions abordées avec les exemples qui vont bien.

Le seul défault est dans la partie `Saut réaliste : vitesse et gravité`.
J'ai peur que les astuces présentées soient trop compliquées à mettre en place.

2022-07-27 18:29 UTC, MrCirdo commented on content/divers/projet_jeu/index.md
> +Pour pallier à cela, une fois que vous avez trouvé le rectangle solide avec lequel vous êtes en collision, vous pouvez effectuer un mouvement de la forme :
```suggestion
Pour pallier cela, une fois que vous avez trouvé le rectangle solide avec lequel vous êtes en collision, vous pouvez effectuer un mouvement de la forme :
```
Juste une typo.

2022-07-27 18:29 UTC, MrCirdo commented on content/divers/projet_jeu/index.md
> +Une fois la vitesse calculée, on change le vecteur $\vec{p}$ en $\vec{p}+\vec{v}$ pour déplacer le personnage[^3].
J'ai compris le principe d'ajouter des nombres à chaque tour à la position de joueur.
Cependant, physiquement c'est faux de faire la somme d'un vecteur vitesse et d'un vecteur position.

2022-07-27 18:29 UTC, MrCirdo commented on content/divers/projet_jeu/index.md
> +Si vous changiez l'image exactement à chaque tour de boucle, l'animation risque d'être beaucoup trop rapide, du coup on préfèrera choisir l'image en fonction de `tour_de_boucle // 50 % 2`, cette vale
Il me semble que les opérateurs `//` et `%` ne sont pas introduits. De mémoire, ils sont mentionés sous forme de question dans le TP d'intro à pyton.
On peut être les introduire ici.
De plus, l'astuce de `tour_de_boucle // 50 % 2` est dur à comprendre.

2022-07-27 18:29 UTC, MrCirdo commented on content/divers/projet_jeu/index.md
> +## Carte d'un niveau
Est-ce une bonne idée de préciser que la carte est intialisée dans la partie initialisation ?
Mais qu'elle peut être modifée dans la partie boucle.

2022-07-27 18:29 UTC, MrCirdo commented on content/divers/projet_jeu/index.md
> +Celle-ci prend un second argument : l'angle de rotation (dans le sens trigonométrique, c'est-à-dire anti-horaire).
```suggestion
Celle-ci prend un second argument : l'angle de rotation en degré (dans le sens trigonométrique, c'est-à-dire anti-horaire).
```
Je préfère rajouter que l'angle est en degré même si on peut le deviner dans l'exemple plus bas.

2022-07-28 15:08 UTC, amelie311098 requested changes
Giga complet comme sujet
Hmm, on vouvoie tout le temps, alors qu'on aimerait tutoyer comme les autres TP
Et je pense qu'il faudrait rajouter plein de rappels et de blocs pour dire "pour résumer" (l'explication), "avancé" (quand ça va un peu loin)

2022-07-28 15:08 UTC, amelie311098 commented on content/divers/projet_jeu/index.md
> +Vous trouverez à peu prêt les mêmes sprites pour les deux personnages suivant :
```suggestion
Vous trouverez à peu près les mêmes sprites pour les trois personnages suivants :
```

2022-07-31 13:21 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/85

2022-07-31 13:21 UTC, closed without merging