Micro morse
prologin/gcc-contenus pull request #86
Opened 2022-07-19 16:38 UTC by Gregoire-perso

Voici un nouveau TP abordant la récursivité et les arbres binaires. Hésitez pas à faire vos retours sur la complexité des notions abordées et surtout si elles sont suffisament bien expliquées

2022-07-20 15:20 UTC, kolowy requested changes
Je trouve ce TP très compliqué, et peu adapté au niveau des participantes dans la plupart des cas.
Cependant il peut être utile dans les cas où des élèves sont très avancés, car il est très intéressant.

2022-07-21 01:25 UTC, Gregoire-perso commented on content/micropython/micro_morse/resources/ref/ref.py
> +# Iterative version
On peut les traduire en français, mais de toutes façons la réf est pas destinée à être donnée aux participantes

2022-07-27 17:30 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +est quelque chose qui va s'appeler lui-même.
Je préférerais qq chose du genre "les fonctions récursives sont des fonctions dont le calcul nécessite d'invoquer la fonction elle-même"

2022-07-27 18:21 UTC, amelie311098 requested changes
Très gros morceau ce TP, bcp de cours à comprendre
Je pense qu'il faudrait le rendre plus visuel, et y aller pas à pas, et non d'un bloc

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +Tu peux utiliser ce code pour représenter les `Noeuds` et tester ton code avec
```suggestion
Tu peux utiliser ce code pour représenter les `Noeud` et tester ton code avec
```

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +    `clé` avant de rechercher la localisation de la boite du `fils droit` puis
Fils gauche en premier

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +- le parcours infixe, celui du mini-exercice, dans lequel on va voir le fils
Potentiellement mettre des schémas avec des nombres pour l'ordre de passage, ou un trait à suivre

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +données. Il est très important que tu ais compris la partie précédente afin
```suggestion
données. Il est très important que tu aies compris la partie précédente afin
```

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +Comme vous pouvez le voir, il suffit de parcourir l'arbre (comme expliqué plus
Pk vouvoyer seulement ici ?

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +_Code à compléter_ en haut de cette page.
Ce bouton existe ?

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +Ces derniers paragraphes ont été assez dense et ne sont pas des plus faciles à
```suggestion
Ces derniers paragraphes ont été assez denses et ne sont pas des plus faciles à
```

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +Si tout est bon pour toi, nous allons pouvoir commencer le coeur de notre TP !
Euh....... Oui, y'a bcp de cours d'un coup donc

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +> microbit
A quel moment on finit une lettre ?

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +Nous devons donc faire attention à ce qu'une mauvais utilisation de la part de
```suggestion
Nous devons donc faire attention à ce qu'une mauvaise utilisation de la part de 
```

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +Ici, la seule erreur que l'utilisateur peut comettre, c'est de valider une
```suggestion
Ici, la seule erreur que l'utilisateur peut commettre, c'est de valider une
```

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/index.md
> +- Pouvoir corriger une faute de frappe en appyuant simultanémant sur `A` et `B`
```suggestion
- Pouvoir corriger une faute de frappe en appuyant simultanément sur `A` et `B`
```

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/resources/given_resources/micro_morse.py
> +    message_recu = radio.receive() # Essaye de recevoir un message
Ici en français mais plus haut en anglais ?
Faudrait tout passer en français je pense

2022-07-27 18:21 UTC, amelie311098 commented on content/micropython/micro_morse/resources/given_resources/micro_morse.py
> +        display.scroll(received_message) # Affiche le message recu s'il existe
'received_message' n'existe pas 👀

2022-07-31 13:21 UTC, kolowy commented
Migrated to https://gitlab.com/prologin/gcc/contenus/-/merge_requests/86

2022-07-31 13:21 UTC, closed without merging